[[LibBirch]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "268384bd7b9efbcbd544252a69a666af6c208011"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "c5adcc6ca241446c21db9594b52abfc1b93d553a4e9290ddb4863e534544fea7"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LibBirch]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e105690ac545ee4e8a10cf623c0437dda8dc9a7e"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "fa6ebb5d382522466221404fad8ba847885aaa689596c02b164a432162572eee"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LibBirch]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87f91d50a622a753ae85fe4431ab9316f38d536f"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "7342229f2025089bef6079b79f57f59d9bce2586ae7805bde23c4cafa5270d13"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.aarch64-linux-musl-cxx03.tar.gz"
[[LibBirch]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a60801df286942bc7d4ae207abda93236741e25"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "bf45431e81209f138ae44afef84a36421b201f59b00942315286b8d77f3caded"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.aarch64-linux-musl-cxx11.tar.gz"
[[LibBirch]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab2e7d0ba8cbfaed2534003d226bc25d75542c6d"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "382850c30593763f7960e7a75f5a6d2f72f119980e665c985afb847c1d4191f9"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LibBirch]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cd56a972901cf5f2b5ab5cccbf50ebd0efe7390"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "d00021e93a3c0a60751976807b571610a720df47337c66b9d36c419e9571f359"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LibBirch]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5526e4b5fc16ddfdf6c7f4c6e171b49dc83a707"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "f87c3e4613b9248d71097369ab090cb414a1106545d0fc7a1d80ca9dc5772ff7"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LibBirch]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a8975284671eab2315ae375de8342e8ee3d67d7"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "d45a0e86500d61dd695188c38a9363a3db4840a9658dd68c99b656914bf8d6a0"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LibBirch]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b28c64f7bf39f22ad9ab5e259e24391ead92efb6"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "42e650c758105b8bc8110ac3fcdfabbe854447c26b254d732f617a5c23a0ee6b"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.i686-linux-gnu-cxx03.tar.gz"
[[LibBirch]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54eeb2026426029820452c388b37c10db6b709e6"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "5eebc0ad663014259352e2b5e6bdf43434470cc38d8bccde46182b8561494956"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.i686-linux-gnu-cxx11.tar.gz"
[[LibBirch]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64d92e41be749573a036a03bf8414930951a692e"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "efa86e5407cef839e6a96a95b47925a5b83dc0d47dc2d729efb4100b5b57fe08"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.i686-linux-musl-cxx03.tar.gz"
[[LibBirch]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73a3f833b5154013d37e3383bbca492a11890fbb"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "1f00bb3780ac9e12be815f5fff3644482dc626b21ee6dc322c40ec4f313eb107"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.i686-linux-musl-cxx11.tar.gz"
[[LibBirch]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daf9ac7073c41013e4cb3ab8082f8d676882b11e"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "3b2888ebf9fb255053905a6d8d597b4a031a04f0a45f5f92b460d0f3dddef25c"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LibBirch]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7649e63732f4361118507fd81705a346936c68bc"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "822ecc7b2d3b92cfa26ecf857af5d64d7275984f10976207de30136e1ff41aa4"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LibBirch]]
arch = "x86_64"
git-tree-sha1 = "c0108110971d4ce5d52c3ebc2792c498f8cf20df"
os = "macos"

    [[LibBirch.download]]
    sha256 = "fe55231404bd167301e2ce42fbb84ace5010e6c02908e651a55e305f1e351316"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-apple-darwin.tar.gz"
[[LibBirch]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2d1d9d8aa9cb4899916e173bbc46278b09159da"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "e1cd6b7caa7bd18eee6937dad34c3c6467defb10e3654f7748638e1404a3bb9c"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LibBirch]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80c020d8cab13a0837a05676833d9022ef5c6f9f"
libc = "glibc"
os = "linux"

    [[LibBirch.download]]
    sha256 = "f481adc12906bb069559df6751015be8ddc9048388e6f33351f1417ccd345451"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LibBirch]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cd040e38f7a94a596168a0f8341c2c7925deea6"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "08dae81154d036f6378d81d57b5c2020f304fe98df044dafe4c59f226119b5ec"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-linux-musl-cxx03.tar.gz"
[[LibBirch]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4762bb3f1759076e597fe86f420631dd010f8e16"
libc = "musl"
os = "linux"

    [[LibBirch.download]]
    sha256 = "574d5ec3ecf3b02e3be65e35cab7d9a5f27f5fa53149cc4bc794f4ca52010174"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-linux-musl-cxx11.tar.gz"
[[LibBirch]]
arch = "x86_64"
git-tree-sha1 = "c012f901f31cd2cabad862219f2120cb1f1211fb"
os = "freebsd"

    [[LibBirch.download]]
    sha256 = "a75fe5c01e92ce596c06f360d0f57eaa01ced2069c086e848ea05d17aef8e03b"
    url = "https://github.com/JuliaBinaryWrappers/LibBirch_jll.jl/releases/download/LibBirch-v1.104.0+0/LibBirch.v1.104.0.x86_64-unknown-freebsd.tar.gz"
